const address = ['Apartment 3, Dhanmondi, Dhaka, Bangladesh - 1207',
    'House 2, Shahbagh, Dhaka, Bangladesh - 1207',
    'Apartment 2, Dhanmondi, Sylhet, Bangladesh - 1205',
    'House 4, Motijheel, Barisal, Bangladesh - 1229',
    'House 4, Banasree, Sylhet, Bangladesh - 1205',
    'Apartment 5, Gulshan, Dhaka, Bangladesh - 1229',
    'Apartment 3, Dhanmondi, Sylhet, Bangladesh - 1230',
    'Apartment 5, Motijheel, Barisal, Bangladesh - 1212',
    'Apartment 4, Motijheel, Barisal, Bangladesh - 1212',
    'House 4, Mirpur Road, Khulna, Bangladesh - 1207',
    'House 2, Gulshan, Sylhet, Bangladesh - 1216',
    'House 3, Motijheel, Rajshahi, Bangladesh - 1230',
    'House 5, Banasree, Chittagong, Bangladesh - 1230',
    'House 2, Banasree, Sylhet, Bangladesh - 1216',
    'House 1, Dhanmondi, Barisal, Bangladesh - 1216',
    'Apartment 3, Mirpur Road, Dhaka, Bangladesh - 1229',
    'Apartment 4, Banasree, Khulna, Bangladesh - 1212',
    'Apartment 2, Dhanmondi, Sylhet, Bangladesh - 1216',
    'Apartment 5, Banasree, Barisal, Bangladesh - 1212',
    'Apartment 1, Shahbagh, Sylhet, Bangladesh - 1207',
    'Apartment 1, Shahbagh, Khulna, Bangladesh - 1207',
    'House 1, Dhanmondi, Chittagong, Bangladesh - 1229',
    'House 3, Shahbagh, Khulna, Bangladesh - 1229',
    'House 1, Motijheel, Chittagong, Bangladesh - 1205',
    'Apartment 4, Dhanmondi, Barisal, Bangladesh - 1230']

module.exports = address