// We have a function that can take two arguments called start and end. Both arguments will be a valid integer number. The function will return a random value in the given range

GET http://localhost:5000/rand?start=5&end=10

###

// We have a function that can generate a fake person profile including first name, last name, email, avatar, age and address. User can pass an array of selected properties and it will return a person object containing only given properties. Ex: generatePerson([’firstName’, ‘lastName’, ‘email’])

http://localhost:5000/fake?specs=fname,lname,age,email,address

###

// We have a function that can accept a string as an argument and return an object containing the number of letters, number of symbols and number of numeric characters.

http://localhost:5000/counter?word=h3110%w0r1d